# Numpy


In [17]:
# numpy --> n dimentional python array (n D) n >=1
import numpy as np 
arr = np.array([1,3,5,7])
print("arr:",arr)
print("arr.ndim:", arr.ndim)
print("arr.shape:", arr.shape)
print("arr.size: ", arr.size)

arr: [1 3 5 7]
arr.ndim: 1
arr.shape: (4,)
arr.size:  4


In [18]:
mat2 = np.array([ [1,3,5], [2,5,8], [5,6,70] ])
print("mat2:",mat2)
print("mat2.ndim:", mat2.ndim)
print("mat2.shape:", mat2.shape)
print("mat2.size: ", mat2.size)

mat2: [[ 1  3  5]
 [ 2  5  8]
 [ 5  6 70]]
mat2.ndim: 2
mat2.shape: (3, 3)
mat2.size:  9


In [19]:
row, col =mat2.shape # returns a tuple
print("num Rows:", row)
print("num Cols:", col)

dim = mat2.shape
print('dim=', dim, 'dim[0]=', dim[0] , 'dim[1]=', dim[1])
# hardest work for computer: matrix multiplicaiton
# numpy made it easy
# GPU only multiply matrix

num Rows: 3
num Cols: 3
dim= (3, 3) dim[0]= 3 dim[1]= 3


In [20]:
# Deep Learning: need GPU --> Need to multiply matrix
mat1 = np.array([ [1, 3, 5], [2, 7, 9], [98, 74, 23] ])
mat3 = np.array([ [1, 3], [7, 9], [74, 23] ])

mat_1_3 = np.dot(mat1, mat3)
print(mat_1_3)

[[ 392  145]
 [ 717  276]
 [2318 1489]]


In [21]:
print( np.matmul(mat1, mat2) )

[[  32   48  379]
 [  61   95  696]
 [ 361  802 2692]]


In [22]:
print( np.log(mat_1_3) )

[[5.97126184 4.97673374]
 [6.57507584 5.62040087]
 [7.74846002 7.30586003]]


In [23]:
for i in mat1:
    print(i, end=' ')

[1 3 5] [2 7 9] [98 74 23] 

In [24]:
for i in mat1:
    for j in i:
        print(j, end=' ')
    print()

1 3 5 
2 7 9 
98 74 23 


Linear Algebra is used in Matrix <br>
Face recognittion used for face recognition --> different Eigen Value for different Face
