In [1]:
print('Welcome to DSP lab')
age = 23 # Number type data
salary = 156000.56 # Number: Float type
name = 'Khan'

print('My name is', name, ' of age ', age, ' Salary', salary)
print("type(age): ", type(age))
print("type(salaray): ", type(salary))
print("type(name): ", type(name))

Welcome to DSP lab
My name is Khan  of age  23  Salary 156000.56
type(age):  <class 'int'>
type(salaray):  <class 'float'>
type(name):  <class 'str'>


In [2]:
# get user input
name1 = input('First Name please: ')
name2 = input('First Name please: ')

age = int(input('Age: '))
print('type(age):', type(age))

fullname = name1+' '+name2
print('Full name: ',fullname)

First Name please: alvi
First Name please: anjojm
Age: 12
type(age): <class 'int'>
Full name:  alvi anjojm


In [3]:
a = 14
b= 14.25

d = 'Hello'

list1 = [1,5,6,'DSP','Noice Cancellation Features', 2+2j]
print(list1)
print(type(list1))

for item in list1:
  print(item, end=' ')

[1, 5, 6, 'DSP', 'Noice Cancellation Features', (2+2j)]
<class 'list'>
1 5 6 DSP Noice Cancellation Features (2+2j) 

In [4]:
import numpy as np
com1 = 3+9j
com2 = 3-9j
com4 = com1/com2
print(com4)

com5 = np.abs(com1) # Amplitude np.abs()
print('amplitude: ',com5)
com6 = np.angle(com1) # Phase np.angle()
print('phase: ',com6,' radian')

(-0.8+0.6j)
amplitude:  9.486832980505138
phase:  1.2490457723982544  radian


In [5]:
# loop in python: for(i=0;i<5;i++)
for i in range(5):
  print(i,end=' ')
print()

for i in range(2, 100, 1):
  if i%2==1:
    print('i=',i,'Lucky')
  else:
    print('i=',i,'Hello')

0 1 2 3 4 
i= 2 Hello
i= 3 Lucky
i= 4 Hello
i= 5 Lucky
i= 6 Hello
i= 7 Lucky
i= 8 Hello
i= 9 Lucky
i= 10 Hello
i= 11 Lucky
i= 12 Hello
i= 13 Lucky
i= 14 Hello
i= 15 Lucky
i= 16 Hello
i= 17 Lucky
i= 18 Hello
i= 19 Lucky
i= 20 Hello
i= 21 Lucky
i= 22 Hello
i= 23 Lucky
i= 24 Hello
i= 25 Lucky
i= 26 Hello
i= 27 Lucky
i= 28 Hello
i= 29 Lucky
i= 30 Hello
i= 31 Lucky
i= 32 Hello
i= 33 Lucky
i= 34 Hello
i= 35 Lucky
i= 36 Hello
i= 37 Lucky
i= 38 Hello
i= 39 Lucky
i= 40 Hello
i= 41 Lucky
i= 42 Hello
i= 43 Lucky
i= 44 Hello
i= 45 Lucky
i= 46 Hello
i= 47 Lucky
i= 48 Hello
i= 49 Lucky
i= 50 Hello
i= 51 Lucky
i= 52 Hello
i= 53 Lucky
i= 54 Hello
i= 55 Lucky
i= 56 Hello
i= 57 Lucky
i= 58 Hello
i= 59 Lucky
i= 60 Hello
i= 61 Lucky
i= 62 Hello
i= 63 Lucky
i= 64 Hello
i= 65 Lucky
i= 66 Hello
i= 67 Lucky
i= 68 Hello
i= 69 Lucky
i= 70 Hello
i= 71 Lucky
i= 72 Hello
i= 73 Lucky
i= 74 Hello
i= 75 Lucky
i= 76 Hello
i= 77 Lucky
i= 78 Hello
i= 79 Lucky
i= 80 Hello
i= 81 Lucky
i= 82 Hello
i= 83 Lucky
i= 84 Hello
i

In [6]:
def factorial(n):
  if n==1:
    return 1;
  else:
    return n*factorial(n-1);

while(True):
  n = int(input('Enter a number(0 to exit): '))
  if n==0:
    break;
  fact = factorial(n)
  print('Factorial of:', n, 'is:', fact)

Enter a number(0 to exit): 7
Factorial of: 7 is: 5040
Enter a number(0 to exit): 0


In [7]:
len(str(factorial(500)))
# we can't get lenth of int --> convert it to string --> calculate length

1135

In [8]:
import numpy as np
# numpy --> strongest array or, matrix

array1 = np.array([[2,3,4],[5,6,7],[8,9,10]])
array2 = np.array([[1,6,7],[2,3,6],[3,8,45]])

print(array1,'\nshape:', array1.shape, '\nndim:', array1.ndim)
print(array2,'\nshape:', array2.shape, '\nndim:', array2.ndim)

mat1_mat2 = np.dot(array1, array2)
print(mat1_mat2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]] 
shape: (3, 3) 
ndim: 2
[[ 1  6  7]
 [ 2  3  6]
 [ 3  8 45]] 
shape: (3, 3) 
ndim: 2
[[ 20  53 212]
 [ 38 104 386]
 [ 56 155 560]]
