In [352]:
import numpy as np
import matplotlib.pyplot as plt

In [353]:
z = np.arange(0,1,.1)

for i in range(len(z)):
    print(f'z[{i}]: {z[i]}')

z[0]: 0.0
z[1]: 0.1
z[2]: 0.2
z[3]: 0.30000000000000004
z[4]: 0.4
z[5]: 0.5
z[6]: 0.6000000000000001
z[7]: 0.7000000000000001
z[8]: 0.8
z[9]: 0.9


In [354]:
# print z[0] to z[9]
print(z[:10])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [355]:
# print z[5] to z[9]
print(z[5:10])

[0.5 0.6 0.7 0.8 0.9]


In [356]:
# print z[5] to last elment
print(z[5:])

[0.5 0.6 0.7 0.8 0.9]


In [357]:
D2 = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print(D2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [358]:
print(D2[:,0])

[1 5 9]


In [359]:
D2[0,:]

array([1, 2, 3, 4])

In [360]:
D2[0:3, 1:4]
# D2[ row_start_index : row_end_index+1 , col_start_index : col_end_index+1 ]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [361]:
# t = np.array( [i/10 for i in range(0,21,1)] )
# t = np.arange(0, 21/10, 1/10)
# t = np.arange(0, 2.1, .1)
t = np.linspace(0, 2, 21) # 0 <= t <= 2 : total 21 points, difference among points equal
t

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [362]:
print(t)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]


In [363]:
t[1]

0.1

In [364]:
t[ t.argmax() ]

2.0

In [365]:
t[-1]

2.0

In [366]:
t[:-1]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [367]:
# Reverse np array
t[::-1]

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. , 0.9, 0.8,
       0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [368]:
# time_indices[::factor] slices the time_indices array starting from the beginning, taking every factor-th element. For example, if factor is 2, it will take every second element from time_indices.
t[::2]

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [369]:
t[::-2]

array([2. , 1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ])

In [370]:
-10*t

array([ -0.,  -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.,
       -11., -12., -13., -14., -15., -16., -17., -18., -19., -20.])

In [371]:
t = np.arange(0, 2, .1)
t

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [372]:
np.sin(np.pi/2)

1.0

In [373]:
np.pi

3.141592653589793

In [374]:
sampling_rate = 3
t = np.arange(0, 2, 1/sampling_rate)

n1, = t.shape # (2-0)* sampling_rate
print('n1: n1,=t.shape :', n1)

n2 = t.shape
print('n2: t.shape :',n2)

n1: n1,=t.shape : 6
n2: t.shape : (6,)


In [375]:
t = np.array( [1+2j, 2-3j, 3+4j, 4-5j] )

In [376]:
print('t', t)
print('t[:]', t[:])
print('t.min() :', t.min())
print('t.max() :', t.max())
print('t.argmin() :', t.argmin())
print('t.argmax() :', t.argmax())
print('t.size :', t.size)
print('len(t) :', len(t))
print('t.shape :', t.shape)
print('t.data :', t.data)
print('t.real :', t.real)
print('t.imag :', t.imag)
print('t.mean() :', t.mean())
print('t.sum() :', t.sum())

t [1.+2.j 2.-3.j 3.+4.j 4.-5.j]
t[:] [1.+2.j 2.-3.j 3.+4.j 4.-5.j]
t.min() : (1+2j)
t.max() : (4-5j)
t.argmin() : 0
t.argmax() : 3
t.size : 4
len(t) : 4
t.shape : (4,)
t.data : <memory at 0x000001D7EC186500>
t.real : [1. 2. 3. 4.]
t.imag : [ 2. -3.  4. -5.]
t.mean() : (2.5-0.5j)
t.sum() : (10-2j)
